name: Release notes

on:
#  push:
#    branches: [ main, 1.0-dev ]
  pull_request:
    branches: [ main, 1.0-dev ]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
